### ISSUE TITLE
Feature request: unicode/widechar search

### ISSUE THREAD

**Issue by sigillaria** [fkie-cad/hexter#1]
As `-fu`, example: `hexter -file filepathname -fu '\\Device\beep' `

That would be cool. :)

**Comment by yehoudie** [comment]
Will think about it. It's difficult to pull of cross os, because a wchar_t on (at least 64-bit) Linux has a size of 4 bytes, on Windows its size is two bytes. For "pseudo" unicode with an ASCII charset it would be easier though.

**Comment by yehoudie** [comment]
Should be working now.
![cmd](https://user-images.githubusercontent.com/8250669/104850442-6b909e80-58ef-11eb-8c39-449d386dc73f.jpg)

**Comment by sigillaria** [comment]
Yes it works! Thanks. :-)
